config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :users, except: [:index] do 
    resources :to_do_lists, shallow: :true do 
      collection do
        put 'complete'
      end
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  validates :user_id, :day, :task, presence: true
  belongs_to :user
end 

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email
  validates_presence_of :name, :email, :password
  validates :password, confirmation: { case_sensitive: true }
  
  has_many :to_do_lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_user
    redirect_to root_path if !current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.now[:notice] = "Logged in as #{current_user.email}"
      redirect_to '/dashboard'
    else
      flash.now[:notice] = "email and/or password may not match in our database"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :check_user

  def index
    @to_do_lists = current_user.to_do_lists 
  end

  def new 
    @to_do_list = current_user.to_do_lists.new
  end

  def create
    @to_do_list = current_user.to_do_lists.new(todo_params)
    if @to_do_list.save
      UserNotifier.send_tasks_email(current_user).deliver_now
      flash[:success] = "Lets get it done!"
      redirect_to user_to_do_lists_path(current_user)
    else
      flash.now[:error] = "OOPS! Something is missing!"
      render :new
    end
  end

  def show
    @to_do_list = current_user.to_do_lists.find
  end

  def destroy
    @to_do_list = ToDoList.find(params[:id])
    @to_do_list.destroy

    redirect_to user_to_do_lists_path(current_user)
  end

  def complete
    ToDoList.where(id: params[:task_ids]).update_all(status: true)
    redirect_to user_to_do_lists_path(current_user)
  end

  private
    def todo_params
      params.require(:to_do_list).permit(:day, :task)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, except: [:new, :create]

  def show;end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{current_user.email}"
      redirect_to '/dashboard'
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    if @user.save
      flash[:notice] = "#{@user.name} was updated"
      redirect_to dashboard_path
    else
      flash.now[:notice] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session.destroy
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
     redirect_to dashboard_path
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_error_messages(type, message)
    if message.is_a?(Array)
      message.map { |msg| content_tag(:li, msg) }.join
    else
      content_tag :div, message, class: type
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  
    <% unless controller_name == "welcome" %>
      <%= render "navigation/nav" %>
    <% end %>
  </head>

  <body>
    <div class="flash">
      <% flash.each do |type, message| %>
        <%= format_error_messages(type, message).html_safe %>
      <% end %>
    </div>

    <%= yield %>
    
    <footer>
      <div class="footer">
        <p>Copyright &copy; ToDoList 2018</p>
      </div>
    </footer>
  </body>
</html>

app/views/navigation/_nav.html.erb
<div class="nav">
  <% if current_user %>
    <%= link_to "Home", dashboard_path(current_user) %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>
</div>

app/views/to_do_lists/index.html.erb
<div class="todo-list">
  <div class="new_list">
    <h1><%= "#{current_user.name}'s To Do List" %></h1>
    <% if @to_do_lists.empty?  %>
      <h3><%= link_to "create a list", new_user_to_do_list_path(current_user) %></h3>
    <% else %>
      <h3><%= link_to "Add a task", new_user_to_do_list_path(current_user) %></h3>
    <% end %>
  </div>

  <% if !@to_do_lists.empty?  %>
    <div class="todos">
      <%= form_tag complete_user_to_do_lists_path, method: :put do %>
        <% @to_do_lists.each do |task| %>
          <% if task.status != true %> 
            <%= check_box_tag "task_ids[]", task.id %>
            Day: <%= task.day %>
            <br>
            Task: <%= task.task %>
            <br>
            <%= link_to "delete", to_do_list_path(task.id), method: "delete", data: {confirm: "Are you sure you want to delete the task?"} %>
            <br>
            <br>
          <% end %>
        <% end %>
        
        <% count = 1 %>
        <% @to_do_lists.each do |task| %>
          <% if task.status != true && count == 1 %>
            <% count += 1 %> 
            <%= submit_tag "Mark as Complete" %>
          <% end %>  
        <% end %>  
        <br>
        <br>
        <br>
      <% end %>

      <% ct_count = 1 %>
      <% @to_do_lists.each do |task| %>
        <% if task.status == true && ct_count == 1 %>
          <% ct_count += 1 %>       
          <h2>Completed Tasks</h2>
        <% end %>
      <% end %>

      <% @to_do_lists.each do |task| %>
        <% if task.status %>
          Day: <%= task.day %>
          <br>
          Task: <%= task.task %>
          <br>
          <%= link_to "delete", to_do_list_path(task.id), method: "delete", data: {confirm: "Are you sure you want to delete the task?"} %>
          <br>
          <br>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/to_do_lists/new.html.erb
<div class="create-task">
  <%= form_for [:user, @to_do_list] do |f| %>
    <%= f.label :day %>
    <%= f.text_field :day %>
    <br>
    <br>
    <%= f.label :task %>
    <%= f.text_area :task %>
    <br>
    <br>
    <%= f.submit "Create Task" %>
  <% end %>
</div>

app/views/user_notifier/send_tasks_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1><%= @user.name %>, here are your new tasks!</h1>
    <p>Time to get to work and have a great day!</p>
    <p>
      <% @user.to_do_lists.each do |list| %>
      <br>
      Day: <%= list.day %>
      <br>
      Task: <%= list.task %>
      <br>
    <% end %>
    </p>
  </body>
</html>

app/views/user_notifier/send_tasks_email.text.erb
<%= @user.name %>, here are your new tasks!
===============================================
 
Time to get to work and have a great day!

<% @user.to_do_lists.each do |list| %>
  Day: <%= list.day %>
  Task: <%= list.task %>
<% end %>

app/views/users/_form.html.erb
<div class="login-form">
  <%= form_for @user,:html=>{:class => 'login-form'} do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <br>
    <%= f.submit "Submit", class: 'btn btn-default btn-lg btn-submit' %>
  <% end %>
  <br>
</div>

app/views/users/edit.html.erb
<div class="edit-new-account">
  <% if current_user %>
    <div class="text-center">
      <h2>Modify Account</h2>
      <br>
      <%= render partial: "form" %>
    </div>
  <% else %>
    <%= render file: 'public/404' %>
  <% end %>
  <%= link_to "cancel", dashboard_path %>
</div>

app/views/users/new.html.erb
<div class="edit-new-account">
  <div class="login">
    <h2>Create Account</h2>
    <br>
    <%= render partial: "form" %>
    <%= link_to "back", dashboard_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
  <h2><%= link_to "#{current_user.name}'s To Do List", user_to_do_lists_path(current_user) %></h2>
  <p>Name: <%= current_user.name %></p>
  <p>Email: <%= current_user.email %></p>
  <br>
  <% if current_user %>
    <%= link_to "Delete Account", user_path(current_user), method: "delete", 
    data: {confirm: "Are you sure you want to delete your account?"} %> -
    <%= link_to "Edit Account Information", edit_user_path(current_user) %> 
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="intro">
  <div class="welcome">
    TO<br>DO<br>LIST
  </div>

  <div class="links">
    <div class="linkit">
      <span class="checkmark"></span>
      <h3><%= link_to "Login", login_path %></h3>
    </div>

    <div class="linkit">
      <span class="checkmark"></span>
      <h3><%= link_to "Create An Account", new_user_path %></h3>
    </div>
  </div>
</div>